redis:
  host: 127.0.0.1
  port: 6379
  db: 5
  taskDb: 15
  password: 123123
database:
  pool_name: mysql_pool
  pool_size: 10
  host: 127.0.0.1
  user: root
  password: 123123
  database: toujia
  port: 3306
  database_uri: 'mysql+pymysql://root:manjiu521@127.0.0.1:3306/toujia'
cache:
  RATE_LIMIT_COUNT: 5
  RATE_LIMIT_WINDOW: 60
key:
  api_id: 123456
  api_hash: f123456fb92ff12345604a123456e2
botFather:
  name: cuilon_bot
  link: https://t.me/123456_bot
  token: 711234565:AAF123456SBCZiXT_IvQ3Tb123456
redisKey:
  adminId: "6412345688"
  adminList: "adminList"
  userBlank: "userBlank"
  userSearchCount: "userSearch:Count"